# AWS Nuke Pipeline Configuration

regions:
  - us-east-1
  - global

account-blocklist:
  - "999999999999" # Placeholder for production account ID to avoid accidents

resource-types:
  excludes:
    - IAMUser
    - IAMRole
    - IAMRolePolicyAttachment
    - IAMPolicy

accounts:
  "320042238431": # Your AWS Account ID
    filters:
      S3Bucket:
        - "appsys-invi-terraform-state" # Do NOT delete the state bucket
      IAMRole:
        - type: glob
          value: "AWSControlTower*"
      IAMRolePolicyAttachment:
        - type: glob
          value: "AWSControlTower*"
      IAMPolicy:
        - type: glob
          value: "AWSControlTower*"
      CloudFormationStack:
        - type: glob
          value: "StackSet-AWSControlTower*"
      CloudFormationStackSet:
        - type: glob
          value: "AWSControlTower*"
      CloudWatchEventsRule:
        - type: glob
          value: "AWSControlTower*"
      CloudWatchEventsTarget:
        - type: glob
          value: "ControlTower*"
      ConfigServiceConfigRule:
        - type: glob
          value: "*" # Control Tower relies heavily on Config Rules
      ConfigServiceConfigurationRecorder:
        - type: glob
          value: "*"
      ConfigServiceDeliveryChannel:
        - type: glob
          value: "*"
      CloudTrailTrail:
        - type: glob
          value: "aws-controltower*"
      EC2VPC:
        - property: tag:Name
          type: contains
          value: "AWSControlTower"
      EC2Subnet:
        - property: tag:Name
          type: contains
          value: "AWSControlTower"
      SSMParameter:
        - type: glob
          value: "/aws/reference/secretsmanager/AWSControlTower*"
